name:               "Multi-Robot Systems Lab"
title:              "Multi-Robot Systems Lab"
description:        "Solving robotics problems through multi-robot approaches."


# URL
url:                http://127.0.0.1:4000
baseurl:
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# scholar
scholar:
  # style: ieee
  bibliography: "**/*.bib"
  repository: "./papers"
  bibliography_template: bibliography
  bibtex_skip_fields: [doi]
  sort_by: year
  order: descending

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/about"
  - name:           "projects"
    href:           "/projects"
  - name:           "publications"
    href:           "/publications"
  - name:           "people"
    href:           "/people"
  - name:           "resources"
    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"

  -
    scope:
      path:         ""
      type:         "projects"
    values:
      layout:       "project-page"


collections:
  publication_tags:
     output: true
     permalink: /publications/:title/index.html

  people:
     output: true
     permalink: /people/:title/index.html

  news_items:
      output: false

  projects:
      output: true
      permalink: /projects/:name
