name:               "Multi-Robot Systems Lab"
title:              "Multi-Robot Systems Lab"
description:        "Solving robotics problems through multi-robot approaches."


# URL
url:                http://127.0.0.1:4000
baseurl:            /dev_website
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Plugins
plugins:
  - jekyll-scholar

# scholar
scholar:
  # style: ieee
  bibliography: "**/*.bib"
  repository: "./papers"
  bibliography_template: bibliography
  bibtex_skip_fields: [doi]
  sort_by: year
  order: descending
  details_layout: "bibtex.html"
  details_link: "[bibtex]"

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/index"
  - name:           "projects"
    href:           "/projects"
  - name:           "publications"
    href:           "/publications"
  - name:           "people"
    href:           "/people"
  - name:           "resources"
    href:           "/resources"
  - name:           "videos"
    href:           "https://www.youtube.com/channel/UC_AgJUMueDFePnVwlLDpVBQ"
    target:         "_blank"

# Sass
sass:
  style:            :compressed
  sass_dir:         "./scss"

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"

  -
    scope:
      path:         ""
      type:         "projects"
    values:
      layout:       "project-page"

collections:
  publication_tags:
     output: true
     permalink: /publications/:title/index.html

  people:
     output: true
     permalink: /people/:title/index.html

  news_items:
      output: false

  projects:
      output: true
